# Generated by Django 6.0.5 on 2026-06-19 10:31

import common.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled Chat', max_length=255)),
                ('repository', models.CharField(blank=True, max_length=512, null=True)),
                ('branch', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.BigIntegerField(default=common.models.get_unix_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(default=common.models.get_unix_timestamp)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('content', models.TextField(default='No content found')),
                ('created_at', models.BigIntegerField(default=common.models.get_unix_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(default=common.models.get_unix_timestamp)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatsession')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
