# Generated by Django 6.0.5 on 2026-06-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_user_github_installation_account_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_oauth_context',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.BigIntegerField(default=1782381734, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.BigIntegerField(default=1782381734),
        ),
    ]
