# Generated by Django 6.0.5 on 2026-06-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_user_github_oauth_context_alter_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.BigIntegerField(default=1782382081, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.BigIntegerField(default=1782382081),
        ),
    ]
