# Generated by Django 6.0.5 on 2026-06-09 09:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRepos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repo_id', models.BigIntegerField(unique=True)),
                ('repo_name', models.CharField(max_length=512)),
            ],
        ),
    ]
