# Generated by Django 6.0.5 on 2026-06-22 13:16

import common.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRepos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repo_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=512)),
                ('full_name', models.CharField(max_length=512)),
                ('private', models.BooleanField(default=False)),
                ('default_branch', models.CharField(default='main', max_length=256)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('not_scanned', 'Not Scanned'), ('scanning', 'Scanning'), ('scanned', 'Scanned')], default='not_scanned', max_length=20)),
                ('created_at', models.BigIntegerField(default=common.models.get_unix_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(default=common.models.get_unix_timestamp)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_repos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RepoBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('commit_sha', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('not_scanned', 'Not Scanned'), ('scanning', 'Scanning'), ('scanned', 'Scanned')], default='not_scanned', max_length=20)),
                ('last_indexed_at', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.BigIntegerField(default=common.models.get_unix_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(default=common.models.get_unix_timestamp)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='github.githubrepos')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('repo', 'name')},
            },
        ),
    ]
