# Generated by Django 6.0.5 on 2026-06-23 10:02

import common.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='repobranch',
            name='commit_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='repobranch',
            name='last_error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='githubrepos',
            name='status',
            field=models.CharField(choices=[('not_scanned', 'Not Scanned'), ('scanning', 'Scanning'), ('scanned', 'Scanned'), ('failed', 'Failed')], default='not_scanned', max_length=20),
        ),
        migrations.AlterField(
            model_name='repobranch',
            name='status',
            field=models.CharField(choices=[('not_scanned', 'Not Scanned'), ('scanning', 'Scanning'), ('scanned', 'Scanned'), ('failed', 'Failed')], default='not_scanned', max_length=20),
        ),
        migrations.CreateModel(
            name='BranchScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commit_sha', models.CharField(max_length=64)),
                ('commit_url', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('scanning', 'Scanning'), ('scanned', 'Scanned'), ('failed', 'Failed')], default='scanning', max_length=20)),
                ('started_at', models.BigIntegerField(default=common.models.get_unix_timestamp)),
                ('completed_at', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(default=common.models.get_unix_timestamp, editable=False)),
                ('repo_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='github.repobranch')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='ScanError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_message', models.TextField()),
                ('error_type', models.CharField(max_length=100)),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(default=common.models.get_unix_timestamp, editable=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.BigIntegerField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('branch_scan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errors', to='github.branchscan')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
